version: '3.7'
services:
  seed_node:
    image: "dse-server:6.8.16"
    environment:
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "DS_LICENSE=accept"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m
    ports:
      - "9042:9042"
      - "7199:7199"
    volumes:
      - ./build/data:/var/lib/cassandra


  pulsar:
    image: "datastax/lunastreaming:2.7.2_1.1.6"
    container_name: pulsar
    environment:
      - PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - '8080:8080'
      - '6650:6650'
    expose:
      - 8080
      - 6650
    command: /bin/bash -c "bin/pulsar standalone -nss"
