site:
  title: DataStax CDC for Apache Cassandra documentation
  url: /docs/cdc-apache-cassandra

content:
  sources:
  - url: ./../..
    branches: HEAD
    start-path: docs/docs-src/core

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
  output_dir: assets

asciidoc:
  attributes:
    source-highlighter: highlightjs
  extensions:
  - ./lib/tabs-block.js
