name: Agents CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'kubernetes/**'
      - '**.md'
      - 'grafana/**'
      - 'prometheus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get project version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Test with Gradle
        env:
          PULSAR_IMAGE: "datastax/lunastreaming:2.8.0_1.1.6"
        run: |
          docker pull gaiaadm/pumba:latest
          ./gradlew -PpulsarRepoUrl=https://repo.datastax.com/artifactory/datastax-public-releases-local test:agent-c3-pulsar test:agent-c4-pulsar
