name: Connectors CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'kubernetes/**'
      - '.github/**'
      - '**.md'
      - 'grafana/**'
      - 'prometheus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get project version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven2-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-maven2-

      - name: Test with Gradle
        env:
          DSE_REPO_USERNAME: ${{ secrets.DSE_REPO_USERNAME }}
          DSE_REPO_PASSWORD: ${{ secrets.DSE_REPO_PASSWORD }}
        run: |
          docker pull gaiaadm/pumba:latest
          ./gradlew -PdseRepoUsername="$DSE_REPO_USERNAME" -PdseRepoPassword="$DSE_REPO_PASSWORD" -PpulsarRepoUrl=https://repo.datastax.com/artifactory/datastax-public-releases-local connector-luna:test connector-pulsar:test
