name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'kubernetes/**'
      - '**.md'
      - 'grafana/**'
      - 'prometheus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ['agent', 'agent-c3', 'agent-c4', 'agent-dse4', 'connector']
        jdk: ['11', '17']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'

      - name: Get project version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Test with Gradle
        env:
          DSE_REPO_USERNAME: ${{ secrets.DSE_REPO_USERNAME }}
          DSE_REPO_PASSWORD: ${{ secrets.DSE_REPO_PASSWORD }}
        run: |
          ./gradlew -PdseRepoUsername=$DSE_REPO_USERNAME -PdseRepoPassword=$DSE_REPO_PASSWORD ${{ matrix.module }}:test
