name: CI

on:
  pull_request:
    branches:
      - master
      - cvs-to-cql # TODO: Remove this branch
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'kubernetes/**'
      - '**.md'
      - 'grafana/**'
      - 'prometheus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        env:
          DSE_REPO_USERNAME: ${{ secrets.DSE_REPO_USERNAME }}
          DSE_REPO_PASSWORD: ${{ secrets.DSE_REPO_PASSWORD }}
        run: |
          ./gradlew -PdseRepoUsername=$DSE_REPO_USERNAME -PdseRepoPassword=$DSE_REPO_PASSWORD \
          build -x test

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        module: ['cdc-backfill-client'] # TODO: Restore 'agent', 'agent-c3', 'agent-c4', 'agent-dse4', 'connector',
        jdk: ['11'] # TODO: Restore '17'
        pulsarImageTag: ['2.10_0.4'] # TODO: Restore '2.8.0_1.1.42', '2.8.3_1.0.11',
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'

      - name: Get project version
        uses: HardNorth/github-version-generate@v1.3.0
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Test with Gradle
        env:
          DSE_REPO_USERNAME: ${{ secrets.DSE_REPO_USERNAME }}
          DSE_REPO_PASSWORD: ${{ secrets.DSE_REPO_PASSWORD }}
        run: |
          ./gradlew -PdseRepoUsername=$DSE_REPO_USERNAME -PdseRepoPassword=$DSE_REPO_PASSWORD \
          -PpulsarImageTag=${{ matrix.pulsarImageTag }} \
          ${{ matrix.module }}:test
