name: Publish documentation to GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Generate agent settings documentation
        run:  ./gradlew agent:run --args="../docs/modules/ROOT/pages"

      - name: Generate connector settings documentation
        run: ./gradlew docs:antoraConfig

      - name: Generate Antora configuration in antora.yml
        run: ./gradlew docs:run --args="modules/ROOT/pages"
      - name: Run Antora
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: site-ghpages.yaml
          site_sources_path: docs
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/site
