name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get project version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build with Gradle
        env:
          DSE_REPO_USERNAME: ${{ secrets.DSE_REPO_USERNAME }}
          DSE_REPO_PASSWORD: ${{ secrets.DSE_REPO_PASSWORD }}
        run: ./gradlew assemble -Pdse4 -PdseRepoUsername=$DSE_REPO_USERNAME -PdseRepoPassword=$DSE_REPO_PASSWORD

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload Connectors Release Tar
        id: upload-connectors-release-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: connector-distribution/build/distributions/cassandra-source-connectors-${{ env.CURRENT_VERSION }}.tar
          asset_name: cassandra-source-connectors-${{ env.CURRENT_VERSION }}.tar
          asset_content_type: application/tar
      - name: Upload Connectors Release Zip
        id: upload-connectors-release-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: connector-distribution/build/distributions/cassandra-source-connectors-${{ env.CURRENT_VERSION }}.zip
          asset_name: cassandra-source-connectors-${{ env.CURRENT_VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Agents Release Tar
        id: upload-agents-release-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-distribution/build/distributions/cassandra-source-agents-${{ env.CURRENT_VERSION }}.tar
          asset_name: cassandra-source-agents-${{ env.CURRENT_VERSION }}.tar
          asset_content_type: application/tar
      - name: Upload Agents Release Zip
        id: upload-agents-release-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-distribution/build/distributions/cassandra-source-agents-${{ env.CURRENT_VERSION }}.zip
          asset_name: cassandra-source-agents-${{ env.CURRENT_VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release Pulsar NAR
        id: upload-release-pulsar-nar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: connector-pulsar/build/libs/pulsar-cassandra-source-${{ env.CURRENT_VERSION }}.nar
          asset_name: pulsar-cassandra-source-${{ env.CURRENT_VERSION }}.nar
          asset_content_type: application/java-archive
      - name: Upload Release Luna NAR
        id: upload-release-luna-nar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: connector-luna/build/libs/luna-cassandra-source-${{ env.CURRENT_VERSION }}.nar
          asset_name: luna-cassandra-source-${{ env.CURRENT_VERSION }}.nar
          asset_content_type: application/java-archive

      - name: Upload Release agent-c3-luna
        id: agent-c3-luna-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-c3-luna/build/libs/agent-c3-luna-${{ env.CURRENT_VERSION }}-all.jar
          asset_name: agent-c3-luna-${{ env.CURRENT_VERSION }}-all.jar
          asset_content_type: application/java-archive
      - name: Upload Release agent-c4-luna
        id: agent-c4-luna-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-c4-luna/build/libs/agent-c4-luna-${{ env.CURRENT_VERSION }}-all.jar
          asset_name: agent-c4-luna-${{ env.CURRENT_VERSION }}-all.jar
          asset_content_type: application/java-archive
      - name: Upload Release agent-dse4-luna
        id: agent-dse4-luna-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-dse4-luna/build/libs/agent-dse4-luna-${{ env.CURRENT_VERSION }}-all.jar
          asset_name: agent-dse4-luna-${{ env.CURRENT_VERSION }}-all.jar
          asset_content_type: application/java-archive

      - name: Upload Release agent-c3-pulsar
        id: agent-c3-pulsar-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-c3-pulsar/build/libs/agent-c3-pulsar-${{ env.CURRENT_VERSION }}-all.jar
          asset_name: agent-c3-pulsar-${{ env.CURRENT_VERSION }}-all.jar
          asset_content_type: application/java-archive
      - name: Upload Release agent-c4-pulsar
        id: agent-c4-pulsar-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-c4-pulsar/build/libs/agent-c4-pulsar-${{ env.CURRENT_VERSION }}-all.jar
          asset_name: agent-c4-pulsar-${{ env.CURRENT_VERSION }}-all.jar
          asset_content_type: application/java-archive
      - name: Upload Release agent-dse4-pulsar
        id: agent-dse4-pulsar-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: agent-dse4-pulsar/build/libs/agent-dse4-pulsar-${{ env.CURRENT_VERSION }}-all.jar
          asset_name: agent-dse4-pulsar-${{ env.CURRENT_VERSION }}-all.jar
          asset_content_type: application/java-archive
